import type { Metadata } from 'next';
// import { Inter } from 'next/font/google';
import { montserrat } from './ui/fonts';
import FooterCatto from './components/FooterCatto/FooterCatto';
import HeaderCatto from './components/HeaderCatto/HeaderCatto';
// import GA4TagCatto from './components/Utils/GA4TagCatto/GA4TagCatto';
import './ui/global.css';

// const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  // alternates: {
  //   canonical: 'https://www.domainName.com/',
  // },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`min-h-[calc(100vh-26rem)] ${montserrat.className} absolute m-0 flex w-screen flex-col overflow-x-hidden bg-gray-800 antialiased`}
      >
        <HeaderCatto />
        <div className="mt-20 flex h-screen">
          <div className="flex-[1] bg-gradient-to-r from-gray-500 to-gray-900"></div>
          <main className="flex-[97] dark:bg-gray-700 bg-gray-200">{children}</main>
          <div className="flex-[2] bg-gradient-to-r from-gray-900 to-gray-500"></div>
        </div>
        <FooterCatto />
      </body>
    </html>
  );
}
